name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set package version
        run: pnpm pkg set version=${{ github.ref_name }} --prefix apps/sentry-client-desktop

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sentry-client-desktop artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-windows-latest
          path: apps/sentry-client-desktop/release

  sign:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-windows-latest
          path: release-windows-latest

      - name: Create directory for signed builds
        shell: bash
        run: mkdir signed_builds

      - name: Sign build Windows exe
        uses: sslcom/actions-codesigner@develop
        with:
          command: sign
          username: ${{ secrets.SSL_USERNAME }}
          password: ${{ secrets.SSL_PASSWORD }}
          totp_secret: ${{ secrets.SSL_TOTP_SECRET }}
          file_path: release-windows-latest/sentry-client-windows.exe
          output_path: signed_builds
      
      - name: Upload signed artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-signed-windows-latest
          path: release-windows-latest

  checksum-and-release:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-signed-windows-latest
          path: release-signed-windows-latest

      - name: Generate checksum
        run: |
          CHECKSUM=$(shasum -a 512 release-signed-windows-latest/signed-builds/sentry-client-windows.exe | cut -f1 -d\\ | xxd -r -p | base64)
          CHECKSUM=$(echo "$CHECKSUM" | tr -d '\r\n')
          echo "SHA512 Checksum: $CHECKSUM"
          cat release-signed-windows-latest/latest.yml
          sed -i '' -e "s#^sha512:.*#sha512: $CHECKSUM#" "release-signed-windows-latest/latest.yml"
          sed -i '' -e "s#^    sha512:.*#    sha512: $CHECKSUM#" "release-signed-windows-latest/latest.yml"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-signed-windows-latest/latest.yml
            release-signed-windows-latest/sentry-client-windows.exe.blockmap
            release-signed-windows-latest/signed-builds/sentry-client-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

