name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set package version
        run: pnpm pkg set version=${{ github.ref_name }} --prefix apps/sentry-client-desktop

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sentry-client-desktop artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-sentry-client-desktop-windows-latest
          path: apps/sentry-client-desktop/release

  sign-and-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create Directory For Signed Build
        shell: bash
        run: mkdir release-sentry-client-desktop-windows-latest/signed_builds

      - name: Sign build
        uses: sslcom/actions-codesigner@develop
        with:
          command: sign
          username: ${{ secrets.SSL_USERNAME }}
          password: ${{ secrets.SSL_PASSWORD }}
          totp_secret: ${{ secrets.SSL_TOTP_SECRET }}
          file_path: release-sentry-client-desktop-windows-latest/sentry-client-windows.exe
          output_path: release-sentry-client-desktop-windows-latest/signed_builds

      - name: Generate checksum
        run: |
          CHECKSUM=$(sha512sum release-sentry-client-desktop-windows-latest/signed_builds/sentry-client-windows.exe | cut -f1 -d\ | xxd -r -p | base64)
          echo "SHA512 Checksum: $CHECKSUM"
          sed -i '' -e "s#^sha512:.*#sha512: $CHECKSUM#" release-sentry-client-desktop-windows-latest/latest.yml
          sed -i '' -e "s#^    sha512:.*#    sha512: $CHECKSUM#" release-sentry-client-desktop-windows-latest/latest.yml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-sentry-client-desktop-windows-latest/latest.yml
            release-sentry-client-desktop-windows-latest/sentry-client-windows.exe.blockmap
            release-sentry-client-desktop-windows-latest/signed_builds/sentry-client-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
